name: movies_repository
description: The repository used to retrieve all the [MoviesClient] methods related to the movies.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  movies_client:
    path: ../movies_client

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1
