name: data_persistence_repository
description: Repository to handle data persistence.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  hive: ^2.2.3
  path_provider: ^2.0.10

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1
